# your domain
domain: rdp-proxypool.herokuapp.com

# database url
database_url: ""

# cloudflare api
cf_email: ""
cf_key: ""

# source definition file
source-files:
  # use web file
  - https://raw.githubusercontent.com/rdp-studio/proxypool-configs/main/source.yaml
